version: '3.8'

services:
  aems:
    build:
      context: .
      dockerfile: ./docker/aems/Dockerfile
    container_name: aems
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app
    networks:
      - aems-network
    depends_on:
      - mysql-aems

  webserver:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - aems
    networks:
      - aems-network

  mysql-aems:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - aems-network

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app
    networks:
      - aems-network

volumes:
  mysql_data:

networks:
  aems-network:
    driver: bridge
